# Site settings
title: Luchenjie Blog
header-img: img/home-bg.jpg
email: lcjfly@gmail.com
description: "Write the code Change the world."
baseurl: ""
url: "http://lcjfly.github.io"
#twitter_username: SBootstrap
github_username:  lcjfly
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
